---
title: "Proportion of visual features"
author: "Pierce Edmiston"
date: "October 27, 2015"
output: 
  html_document:
    theme: flatly
---

```{r, echo = FALSE}
library(dplyr)
library(tidyr)

library(lme4)
library(broom)
library(AICcmodavg)

library(ggplot2)
library(scales)

knitr::opts_chunk$set(message = FALSE, warning = FALSE)

devtools::load_all("propertyverification")
data(property_verification)

# Create contrast variables
# -------------------------
property_verification <- property_verification %>%
  recode_mask_type %>%
  recode_feat_type %>%
  recode_exp

# Drop outlier subjects
# ---------------------
property_verification <- filter(property_verification,
                                subj_id %nin% cue_first_outliers,
                                subj_id %nin% question_first_outliers)
```

Our prediction is that categories with a higher proportion of visual features
will be less affected by the order of presentation.

```{r, proportion-visual-categories}
cue_info <- property_verification %>%
  group_by(cue) %>%
  summarize(prop_visual = mean(prop_visual)) %>%
  mutate(cue = reorder(cue, prop_visual)) %>%
  arrange(prop_visual)

ggplot(cue_info, aes(cue, prop_visual, fill = cue)) +
  geom_bar(stat = "identity") +
  scale_y_continuous("Proportion of category features that are visual",
                     labels = percent) +
  guides(fill = "none") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.ticks = element_blank()
  )

ggplot(cue_info, aes(x = prop_visual)) +
  geom_density(fill = "gray")
```

```{r}
effect_of_mask_by_cue <- property_verification %>%
  filter(feat_type == "visual") %>%
  group_by(exp, cue, prop_visual, mask_type) %>%
  summarize(error_rate = mean(is_error, na.rm = TRUE)) %>%
  spread(mask_type, error_rate) %>%
  mutate(effect_of_mask = mask - nomask) %>%
  select(-(mask:nomask))

ggplot(effect_of_mask_by_cue, aes(x = prop_visual, y = effect_of_mask, color = exp)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
mod <- glmer(is_error ~ mask_c * prop_visual * exp_c + (1|subj_id),
             data = filter(property_verification, feat_type == "visual"),
             family = binomial)
summary(mod)

cue_first <- glmer(is_error ~ mask_c * prop_visual + (1|subj_id),
                   data = filter(property_verification, feat_type == "visual", exp == "cue_first"),
                   family = binomial)
summary(cue_first)
```