exp:
	diff -b first_run/MWPF2.py second_run/question_first.py
trials:
	diff -b first_run/MWPF2_trials.py second_run/question_first_trials.py
config:
	diff -b first_run/MWPF2.yaml second_run/question_first.yaml
