# Feature Last

```{r setup, message = FALSE, warning = FALSE, echo = FALSE, cache = FALSE}
library(knitr)
opts_chunk$set(cache = FALSE, cache.path = "feature-last.cache/", 
               warning = FALSE, message = FALSE,
               tidy = TRUE, tidy.opts = list(width.cutoff = 100))

knit_hooks$set(htmlcap = function(before, options, envir) {
  if(!before) {
    paste('<p class="caption" align="center">',options$htmlcap,"</p>",sep="")
  }
})

library(dplyr)
library(lme4)
library(reshape2)
library(AICcmodavg)
library(ggplot2)
library(grid)
library(gridExtra)
library(scales)
library(RColorBrewer)

source("./helper/report-stats.R")       # formatting lmer model output
source("./helper/within-subj-error.R")  # computing within-subject error
source("./helper/helper-funcs.R")       # import `%nin%` function for filtering
source("./helper/lmer-help.R")          # import `get_estimates` for plotting
```

```{r load-data, echo = 1, eval = 1}
df <- read.csv("./feature-last/feature-last-final.csv", stringsAsFactors = FALSE)
df <- filter(df, subj_id != "MWPF214")
```

# Descriptive stats

```{r descriptive, echo = 7, fig.show = 'hold', fig.width = 6, fig.height = 6, fig.align = 'center'}
subjs <- df %.% 
  group_by(subj_id) %.% 
  summarize(
    rt = mean(rt, na.rm = T),
    err = mean(is_error, na.rm = T)
  ) %.% 
  mutate(
    rank_rt = rank(rt, ties.method = "random"),
    rank_err = rank(err, ties.method = "random")
  )

ggplot(subjs, aes(x = rank_rt, y = rt, label = subj_id, color = subj_id)) +
  geom_point() +
  geom_text(hjust = 0, vjust = -0.5, angle = 45, size = 4) +
  coord_cartesian(xlim = c(0.5, 27), ylim = c(100, 1000)) +
  scale_x_continuous("Subject (Ranked By RT)", breaks = c(1, seq(5, 45, by = 5), 46)) +
  scale_y_continuous("Average RT (ms)") +
  theme(legend.position = "none")

ggplot(subjs, aes(x = rank_err, y = err, label = subj_id, color = subj_id)) +
  geom_point() +
  geom_text(hjust = 0, vjust = -0.5, angle = 45, size = 4) +
  coord_cartesian(xlim = c(0.5, 27), ylim = c(0.0, 0.21)) +
  scale_x_continuous("Subject (Ranked By Error Rate)", breaks = c(1, seq(5, 45, by = 5), 46)) +
  scale_y_continuous("Error Rate", label = percent) +
  theme(legend.position = "none")
```

```{r exclude-bad-subjs}
df <- filter(df, subj_id != "MWPF214")
```

# Discrete question type

## Summary

```{r summary, echo = FALSE}
df %.% 
  group_by(subj_id, feat_type, mask_type) %.%
  summarize(
    is_error = mean(is_error, na.rm = TRUE)
  ) %.% ungroup() %.%
  group_by(feat_type, mask_type) %.%
  summarize(
    is_error = mean(is_error)
  )
```

## Models

```{r mod-discrete, echo = 3}
arrange(unique(df[,c("mask_type", "mask_c", "feat_type", "feat_c")]), mask_c, feat_type)

mod_discrete_err <- glmer(is_error ~ feat_c * mask_c + (1|subj_id), data = df, family = binomial)
summarize_glmer(mod_discrete_err, vars = c("feat_c", "mask_c", "feat_c:mask_c"))
```

## Compare question types without visual interference

```{r compare-nomask, echo = c(1, 4)}
df_nomask <- filter(df, mask_type == "nomask")
arrange(unique(df_nomask[,c("mask_type", "feat_type", "feat_c")]), feat_type)

mod_nomask_err <- glmer(is_error ~ feat_c + (1|subj_id), data = df_nomask, family = binomial)
summarize_glmer(mod_nomask_err, vars = "feat_c")
```

## Simple effect of mask on nonvisual questions

```{r mask-on-nonvis, echo = c(1, 4)}
df_nonvisual <- filter(df, feat_type == "nonvisual")
arrange(unique(df_nonvisual[,c("mask_type", "mask_c", "feat_type")]), mask_c)

mod_nonvis_err <- glmer(is_error ~ mask_c + (1|subj_id), data = df_nonvisual, family = binomial)
summarize_glmer(mod_nonvis_err, vars = "mask_c")
```

## Simple effect of mask on visual questions

```{r mask-on-vis, echo = c(1, 4)}
df_visual <- filter(df, feat_type == "visual")
arrange(unique(df_visual[,c("mask_type", "mask_c", "feat_type")]), mask_c)

mod_vis_err <- glmer(is_error ~ mask_c + (1|subj_id), data = df_visual, family = binomial)
summarize_glmer(mod_vis_err, vars = "mask_c")
```

## Plot

```{r plot-discrete, echo = FALSE, fig.width = 10, fig.height = 10, fig.align = 'center'}
base_theme <- theme(
  text = element_text(family = "Helvetica", color = 'black', size = 8),
  line = element_line(color = 'black', size = 0.3),
  panel.background = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(color = 'black'),
  axis.text = element_text(color = 'black', size = 8),
  axis.title = element_text(vjust = 0.3, size = 8),
  axis.ticks.x = element_line(color = 'black'),
  axis.ticks.y = element_line(color = 'black'),
  axis.ticks.length = unit(4, 'points'),
  legend.direction = "vertical",
  legend.background = element_blank(),
  legend.key = element_blank(),
  legend.text = element_text(size = 8),
  legend.title = element_text(size = 8, face = "plain"),
  legend.key.size = unit(10, units = "points"),
  plot.margin = unit(c(0.2,0,0,0), units = "in")
)

nointer_inter <- c("#92c5de", "#ca0020")

# ------------------------------------------------------------------------------

df <- read.csv("./feature-last/feature-last-final.csv", stringsAsFactors = FALSE)
df <- filter(df, subj_id != "MWPF214")

# ------------------------------------------------------------------------------
# Discrete question type

mod <- glmer(is_correct ~ feat_c * mask_c + (1|subj_id), data = df, family = binomial)
x_preds <- unique(df[,c("feat_type", "feat_c", "mask_type", "mask_c")])
y_preds <- predictSE(mod, x_preds, type = "response", se.fit = TRUE)
acc_mean_se <- cbind(x_preds, y_preds) %.%
  mutate(
    feat_type = factor(feat_type, levels = c("nonvisual", "visual")),
    mask_type = factor(mask_type, levels = c("nomask", "mask"))
  ) %.%
  select(feat_type, mask_type, is_correct = fit, mean_se = se.fit) %.%
  arrange(feat_type, mask_type)

acc_diff_se <- df %.%
  summarySEwithin(measurevar = "is_correct", na.rm = TRUE, idvar = "subj_id",
                  withinvars = c("feat_type", "mask_type")) %.%
  mutate(
    feat_type = factor(feat_type, levels = c("nonvisual", "visual")),
    mask_type = factor(mask_type, levels = c("nomask", "mask"))
  ) %.% 
  select(feat_type, mask_type, diff_se = se, ci) %.%
  arrange(feat_type, mask_type)

acc_means <- merge(acc_mean_se, acc_diff_se)

discrete_plot <- ggplot(acc_means, aes(x = feat_type, y = is_correct, fill = mask_type)) +
  geom_bar(aes(fill = mask_type), stat = "identity", position = position_dodge(width = 0.6),
    color = "black", width = 0.6, size = 0.3) +
  geom_bar(aes(y = is_correct - 0.01, fill = mask_type), stat = "identity", position = position_dodge(width = 0.6),
           width = 0.59) +
  geom_errorbar(aes(ymin = is_correct - mean_se, ymax = is_correct + mean_se), 
    position = position_dodge(width = 0.6), size = 0.4, width = 0.1) +
  coord_cartesian(ylim = c(0.70, 1.00)) +
  scale_y_continuous("Accuracy", breaks = seq(0,1,by=0.05), labels = percent) +
  scale_x_discrete("", labels = c("Nonvisual Feature Question", "Visual Feature Question")) +
  scale_fill_manual("", labels = c("No Interference", "Visual Interference"), values = nointer_inter) +
  base_theme + theme(
    legend.position = c(0.8, 0.96)
  )
discrete_plot
```

# Continous Question Ratings

```{r norms, echo = FALSE}
ratings <- read.csv("./feature-norms/feature_norms.csv", stringsAsFactors = FALSE)
summary(ratings[,c("question", "count", "imagery_mean", "facts_mean", "difficulty_mean")])
cor(ratings[,c("imagery_mean", "facts_mean", "difficulty_mean")])
```

## Imagery

```{r mod-imag, echo = 1}
mod_imag_err <- glmer(is_error ~ imagery_z * mask_c + (1|subj_id), data = df, family = binomial)
summarize_glmer(mod_imag_err, vars = c("imagery_z", "mask_c", "imagery_z:mask_c"))
```

### Imagery without mask

```{r mod-imag-nomask, echo = c(1, 3)}
df_nomask <- filter(df, mask_type == "nomask")

mod_imag_nomask_err <- glmer(is_error ~ imagery_z + (1|subj_id), data = df_nomask, family = binomial)
summarize_glmer(mod_imag_nomask_err, vars = "imagery_z")
```

### Imagery with mask

```{r mod-imag-mask, echo = c(1, 3)}
df_mask <- filter(df, mask_type == "mask")

mod_imag_mask_err <- glmer(is_error ~ imagery_z + (1|subj_id), data = df_mask, family = binomial)
summarize_glmer(mod_imag_mask_err, vars = "imagery_z")
```

```{r mod-imag-plot, echo = FALSE, fig.width = 10, fig.height = 10, fig.align = 'center'}
base_theme <- theme(
  text = element_text(family = "Helvetica", color = 'black', size = 8),
  line = element_line(color = 'black', size = 0.3),
  panel.background = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(color = 'black'),
  axis.text = element_text(color = 'black', size = 8),
  axis.title = element_text(vjust = 0.3, size = 8),
  axis.ticks.x = element_line(color = 'black'),
  axis.ticks.y = element_line(color = 'black'),
  axis.ticks.length = unit(4, 'points'),
  legend.direction = "vertical",
  legend.background = element_blank(),
  legend.key = element_blank(),
  legend.text = element_text(size = 8),
  legend.title = element_text(size = 8, face = "plain"),
  legend.key.size = unit(10, units = "points"),
  plot.margin = unit(c(0.2,0,0,0), units = "in")
)

nointer_inter <- c("#92c5de", "#ca0020")

# ------------------------------------------------------------------------------

df <- read.csv("./feature-last/feature-last-final.csv", stringsAsFactors = FALSE)
df <- filter(df, subj_id != "MWPF214")

# ------------------------------------------------------------------------------

question_means <- df %.% 
  group_by(imagery_mean = cut(imagery_mean, breaks = seq(0, 3.5, by = 0.25), labels = seq(0.125, 3.375, by = 0.25), right = FALSE), mask_type) %.%
  summarize(
    obs = n(),
    se = sd(is_correct, na.rm = TRUE) / sqrt(obs),
    is_correct = mean(is_correct, na.rm = TRUE)
  ) %.% ungroup() %.%
  mutate(
    imagery_mean = as.numeric(levels(imagery_mean))[imagery_mean],
    mask_type = factor(mask_type, levels = c("nomask", "mask"))
  )

mod_imag_acc <- glmer(is_correct ~ imagery_mean * mask_c + (1|subj_id), data = df, family = binomial)
x_preds <- expand.grid(imagery_mean = seq(min(df$imagery_mean), max(df$imagery_mean), by = 0.05),
                       mask_c = c(-0.5, 0.5))
y_preds <- predictSE(mod_imag_acc, x_preds, type = "response", se = TRUE)
preds <- cbind(x_preds, y_preds) %.%
  mutate(
    is_correct = fit,
    mask_type = ifelse(mask_c == -0.5, "nomask", "mask"),
    mask_type = factor(mask_type, levels = c("nomask", "mask"))
  )

continuous_estimates <- ggplot() +
  geom_smooth(aes(x = imagery_mean, y = is_correct, color = mask_type, 
    ymin = is_correct - se.fit, ymax = is_correct + se.fit, linetype = mask_type), data = preds, stat = "identity",
    show_guide = FALSE) +
  geom_line(aes(x = imagery_mean, y = is_correct, color = mask_type, 
                  ymin = is_correct - se.fit, ymax = is_correct + se.fit, linetype = mask_type), data = preds, stat = "identity") +
  geom_point(aes(x = imagery_mean, y = is_correct, color = mask_type, size = obs,
                 shape = mask_type), data = question_means, position = position_jitter(width = 0.06, height = 0.0)) +
  # geom_linerange(aes(x = imagery_mean, y = is_correct, color = mask_type, 
  #   ymin = is_correct - se, ymax = is_correct + se), data = question_means) +
  scale_y_continuous("Accuracy", breaks = seq(0,1,by=0.05), labels = percent) +
  scale_x_continuous("\"How much is it necessary to picture the object in your mind's eye?\"", 
                     breaks = seq(0, 3.5, by = 0.25), 
                     labels = c("None", "", "", "", "Little", "", "", "", "Some", "", "", "", "A Lot", "", "")) +
  scale_color_manual("", labels = c("No Interference", "Visual Interference"), values = nointer_inter) +
  scale_linetype_manual("", labels = c("No Interference", "Visual Interference"), values = c(3, 1)) +
  scale_shape_discrete("", labels = c("No Interference", "Visual Interference"), solid = TRUE) +
  scale_size_continuous(range = c(1,3)) +
  coord_cartesian(ylim = c(0.70, 1.00)) +
  guides(size = "none", fill = "none") +
  base_theme +
  theme(
    legend.position = c(0.2, 0.2),
    legend.key.size = unit(18, units = "points"),
    plot.margin = unit(c(-0.1, 0, 0, 0), units = "in")
  )
continuous_estimates
```

## Facts

```{r mod-facts, echo = 1}
mod_facts_err <- glmer(is_error ~ facts_z * mask_c + (1|subj_id), data = df, family = binomial)
summarize_glmer(mod_facts_err, vars = c("facts_z", "mask_c", "facts_z:mask_c"))
```

## Difficulty

```{r mod-diff}
mod_diff_err <- glmer(is_error ~ diff_z * mask_c + (1|subj_id), data = df,
                      family = binomial)
summarize_glmer(mod_diff_err, vars = c("diff_z", "mask_c", "diff_z:mask_c"))
```
